# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    employee.repository:
        class: Infrastructure\Employee\Repository\EmployeeRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Component\Employee\Employee'
