# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    al.employee.model: 'Al\Component\Employee\Employee'

services:
    employee.repository:
        class: 'Al\Infrastructure\Employee\Repository\EmployeeRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%al.employee.model%'

    hautelook_alice.locator.env_directory:
        class: 'Al\Infrastructure\Fixtures\FileLocator'
