services:
    ### Repository
    al.employee.repository:
        class: 'Al\ResourceManagement\Infrastructure\Persistence\Doctrine\EmployeeRepository'
        arguments:
            - '@doctrine.orm.entity_manager'

    al.employee.query:
        class: 'Al\ResourceManagement\Infrastructure\Persistence\Doctrine\ListEmployeeQuery'
        arguments:
            - '@doctrine.orm.entity_manager'

    ### Command handler
    al.employee.handler.hire:
        class: 'Al\ResourceManagement\Application\Handler\HireEmployeeHandler'
        arguments:
            - '@al.employee.repository'
        tags:
            - { name: command_handler, handles: hire_employee }

    al.employee.handler.promote:
        class: 'Al\ResourceManagement\Application\Handler\PromoteEmployeeHandler'
        arguments:
            - '@al.employee.repository'
        tags:
            - { name: command_handler, handles: promote_employee }

    al.employee.handler.fire:
        class: 'Al\ResourceManagement\Application\Handler\FireEmployeeHandler'
        arguments:
            - '@al.employee.repository'
        tags:
            - { name: command_handler, handles: fire_employee }

    ### Event subscriber
    al.employee.event_subscriber.flash_message:
        class: 'Al\ResourceManagement\Infrastructure\Framework\FlashMessageSubscriber'
        arguments:
            - '@session'
        tags:
            - { name: event_subscriber, subscribes_to: employee_hired, method: sendHiredFlashMassage }
            - { name: event_subscriber, subscribes_to: employee_promoted, method: sendPromotedFlashMassage  }
            - { name: event_subscriber, subscribes_to: employee_fired, method: sendFiredFlashMassage  }

    ### Fixture loading
    hautelook_alice.locator.env_directory:
        class: 'Al\ResourceManagement\Infrastructure\Persistence\Doctrine\Fixtures\FileLocator'
